### ISSUE TITLE
[実行委員会への質問]リスクアセスメントシートの提出方法について

### ISSUE THREAD

**Issue by kawazap** [scramble-robot/CoRE-Rulebook#11]
### チーム名

チーム薩摩

### 記入者氏名

川原弘暉

### ルールブックへの質問・意見ではない

- [ ] はい、ルールブックに関する質問・意見ではありません。

### 実行委員会への質問・意見内容を記入してください

リスクアセスメントシートの提出〆切が、3/6(水)に以前設定されていました。[該当URL](https://core.scramble-robot.org/2023/09/11/2825/)
リスクアセスメントシートの提出方法について、メールやGoogleフォームなどの手段があるかどうかに関する情報が案内されていないように思います。
万が一、事前に提出方法が共有されていた場合、誤って見落としてしまった可能性がございます。お手数をおかけしますが、もし提出方法に関する案内がありましたら、改めてご教示いただけますでしょうか。
ご確認のほど、よろしくお願いいたします。

**Comment by tkawasetsu** [comment]
実行委員会の川節です。
リスクアセスメントシートは、各チームへメールでご連絡しているその他の応募シートなどを格納いただくGoogleドライブ内へ保存いただくようお願いいたします。
ご案内が漏れておりお手数をおかけし申し訳ありませんでした。

**Comment by kawazap** [comment]
ご多用の中、ご連絡ありがとうございます。
提出方法について、承知いたしました。
今後ともよろしくお願いいたします。
