### ISSUE TITLE
[ルール変更提案] ベースプレートの設置高さ基準について

### ISSUE THREAD

**Issue by hidaka301** [scramble-robot/CoRE-Rulebook#3]
### チーム名

TKG

### 記入者氏名

日髙　賢太

### どのルールブックのルールの変更を提案しますか？

共通

### どの章のルールの変更を提案しますか？

8章　ダメージパネルの規則

### どのルールの変更を提案しますか？

ルール文面では下記の通りでベースプレートを基準としています。図ではLEDバンパーを基準にしています。
LEDバンパーとベースプレート　どちらを高さの基準にすればよいか確認させてください。またLEDバンパーを基準とするでのあれば下部LEDバンパーの最下端　と表記変更を提案します。

----以下ルール文面----

「下図に⽰すように、床からベースプレートの最下端までの距離が200mm-300mm以内に収まるように取り付け、競技中に⾼さが⼤きく変化しないようにすること。なお、フライングディスクや段差等への乗り上げによる⼀時的な⾼さの変化は許容する。」

![core0_8_damagePanel3](https://github.com/scramble-robot/CoRE-Rulebook/assets/154681504/9230bb4d-4956-4700-92ee-abe3221a7975)

### そのルールを変更する目的はなんですか？

ルール定義の明確化

### そのルールが変更されることによって生じる懸念はありますか？

高さ基準変更による設計修正。

### 何故そのルールが現状のルールブックに記載されているのだと思いますか？

パネル位置基準の明確化

### そのルールの変更によって影響を受けるチーム・人は誰ですか？

全チームに影響する内容になります。
高さをギリギリで設計していた場合はH/W修正が必要になります。

**Comment by kaito0617** [comment]
CoRE競技委員の水野です．
ご指摘の件，混乱を招いてしまい申し訳ございません．
ダメージパネルの設置高さですが，図のLEDバンパー最下端を基準とした計測が正しく，本文のベースプレート最下端は誤りとなっております．
参加者の皆様から他にご意見がなければ，基準をLEDバンパーの最下端に統一し，ルールを下記のように修正したいのですがいかがでしょうか？
- 下図に⽰すように、床から下部LEDバンパーの最下端までの距離が200mm-300mm以内に収まるように取り付け、競技中に⾼さが⼤きく変化しないようにすること。なお、フライングディスクや段差等への乗り上げによる⼀時的な⾼さの変化は許容する。

**Comment by hidaka301** [comment]
ご回答ありがとうございます。ルール修正の件、承知いたしました。
