### ISSUE TITLE
実行委員会への質問・意見　盾の破損について

### ISSUE THREAD

**Issue by Fujii1222** [scramble-robot/CoRE-Rulebook#4]
### チーム名

機襲藩

### 記入者氏名

藤井　咲太朗

### ルールブックへの質問・意見ではない

- [X] はい、ルールブックに関する質問・意見ではありません。

### 実行委員会への質問・意見内容を記入してください

先日フリスビーの射出実験をしていたら、ヒットポイントの左上の３Dプリンターパーツの部分が割れてしまいました。盾が破損してしまった場合どうすればいいでしょうか？ご迷惑をおかけしてすいません。

**Comment by kaito0617** [comment]
CoRE競技委員の水野です．

回答が遅くなってしまい大変申し訳ございません．
ダメージパネルの破損についてですが，先程メールで送付させていただいたフォームより破損状況を送信していただいてよろしいでしょうか？

よろしくお願いいたします．
