### ISSUE TITLE
[ルール変更提案] 盾の進入禁止領域について

### ISSUE THREAD

**Issue by gpgpc0** [scramble-robot/CoRE-Rulebook#5]
### チーム名

機襲藩

### 記入者氏名

巻渕 友慎

### どのルールブックのルールの変更を提案しますか？

共通

### どの章のルールの変更を提案しますか？

8章　ダメージパネルの規則

### どのルールの変更を提案しますか？

以下ルール内容
---
下図に⽰すように、取り付け⾯を左右に20mm延⻑した平⾯から上下120°、左右135°の領域内は競技中を通して⾃ロボットの構造物、および⾃ロボットが保持している強化素材・フライングディスクが侵⼊してはならない。
[https://github.com/scramble-robot/CoRE-Rulebook/blob/main/core_common_image/core0_8_damagePanel4.jpg](url)
---
ルールの側面図によるとLEDバンパーの先端から進入禁止領域が平行に伸びているように見えるのですがこのような解釈でよろしいでしょうか？
できればもう少し側面図の盾の大きさを縮小して全体を見せていただければありがたいです。

### そのルールを変更する目的はなんですか？

ルール定義の明確化

### そのルールが変更されることによって生じる懸念はありますか？

盾の取り付け位置の変化による設計修正
実装できる機能の減少

### 何故そのルールが現状のルールブックに記載されているのだと思いますか？

盾を完全に覆う設計の禁止

### そのルールの変更によって影響を受けるチーム・人は誰ですか？

全チームに影響する可能性があります。
進入禁止領域の場所に意図せずかぶる場合再設計する必要が出るかもしれません。

**Comment by kaito0617** [comment]
CoRE競技委員の水野です．
ご指摘の件ですが，添付の図に示すような放射状に広がる領域が正しいダメージパネルの侵入領域となります．
参加者の皆様から他にご意見がなければ，添付の図をルールに追加し，記述を下記のように修正したいのですがいかがでしょうか？

- 下図に⽰す放射状の領域内はダメージパネルの侵入禁止領域である。侵入禁止領域は、競技中を通して⾃ロボットの構造物、および⾃ロボットが保持している強化素材・フライングディスクが侵⼊してはならない。
![f41](https://github.com/scramble-robot/CoRE-Rulebook/assets/117998441/82e61150-6df0-4357-9d09-c4160a727517)
![f4](https://github.com/scramble-robot/CoRE-Rulebook/assets/117998441/82f2f8c8-54df-427f-83af-b41dab2f7c1d)

**Comment by gpgpc0** [comment]
ご回答ありがとうございます。
その件について了解しました。

**Comment by gpgpc0** [comment]
すみません。ご操作でリオープンしてしまいました。
