### ISSUE TITLE
[実行委員会への質問]　大会当日のロボットの運搬について

### ISSUE THREAD

**Issue by NaokiMiyamura** [scramble-robot/CoRE-Rulebook#6]
### チーム名

SETAGAYA Eclipse

### 記入者氏名

宮村 直希

### ルールブックへの質問・意見ではない

- [x] #7

### 実行委員会への質問・意見内容を記入してください

大会当日のロボットの搬入・搬出についての質問です。
私たちのチームでは、ロボットの運搬にJITBOXを利用することを考えています。
以下２点について回答よろしくお願いします。
1. 搬入・搬出可能な日時を教えてください
2. 仮に搬入可能な日時に私たちが到着できない場合に、大会運営に代わりに荷物を受け取ってもらうことは可能でしょうか

**Comment by tkawasetsu** [comment]
搬入に関して、3月22日（金）は実行委員会が会場で終日設営作業をしているため、受け取りは可能です。
搬出に関して、細かい時間指定が可能なら3月24日（日）の選手権終了後17～20時頃で会場から搬出いただけます。24日中が難しい場合、25日（月）夕方頃までであれば実行委員会の方で対応はできると思います。

いずれの場合も実行委員会の対応が必要かどうかも含め、近日中にメールでご案内するロボットの搬入搬出方法へのアンケートにて希望をお知らせください。希望調査後、個別調整が必要なチームに関してはメールで連絡いたします。

**Comment by NaokiMiyamura** [comment]
SECの宮村です。

対応ありがとうございます。
アンケートの件も承知しました。
